### ISSUE TITLE
Auto-pagination for more than 5000 rows seems broken

### ISSUE THREAD

**Issue by vthiery** [apache/cassandra-gocql-driver#1511] opened 2020-11-24 12:43 UTC
### What version of Cassandra are you using?

3.11.3

### What version of Gocql are you using?

v0.0.0-20201024154641-5913df4d474e

### What did you do?

In one of our services, we noticed that scanning through more than 5000 rows was not working properly.
To recreate the issue, I started a container from the Docker image `cassandra:3.11.3`, filled it with 5001 values and tried to scan through them. Here is the schema:

```cql
CREATE KEYSPACE toto
    WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};

CREATE TABLE toto.main (
    id int,
    value double,
    PRIMARY KEY (id)
);
```

and the code I used to reproduce the issue:

```go
package main

import (
	"context"
	"flag"
	"fmt"
	"math/rand"
	"time"

	"github.com/gocql/gocql"
	"github.com/scylladb/gocqlx/qb"
	log "github.com/sirupsen/logrus"
)

func main() {
	nbIDs := flag.Int("n", 1000, "Number of ids to write & read")
	flag.Parse()

	log.Infof("Will write then read %d values", *nbIDs)

	cluster := gocql.NewCluster("localhost:9042")
	cluster.Timeout = 5 * time.Second

	session, err := cluster.CreateSession()
	if err != nil {
		log.Fatalf("could not create the CQL session: %v", err)
	}
	defer session.Close()

	ctx := context.Background()

	ids := generateIDs(*nbIDs)

	if err := write(ctx, session, ids); err != nil {
		log.Fatal(err)
	}

	values, err := read(ctx, session, ids)
	if err != nil {
		log.Fatal(err)
	}
	if n := len(values); n != *nbIDs {
		log.Fatalf("only got %d rows instead of %d", n, *nbIDs)
	}
	log.Info("All good!")
}

func generateIDs(n int) []uint32 {
	res := []uint32{}
	for i := 0; i < n; i++ {
		res = append(res, uint32(i))
	}
	return res
}

func write(ctx context.Context, session *gocql.Session, ids []uint32) error {
	statement, _ := qb.Insert("toto.main").Columns("id", "value").ToCql()
	for _, id := range ids {
		query := session.Query(statement, id, rand.Float64())
		if err := query.Exec(); err != nil {
			return fmt.Errorf("failed to write a value for id %d: %w", id, err)
		}
	}
	return nil
}

func read(ctx context.Context, session *gocql.Session, ids []uint32) (map[uint32]float64, error) {
	statement, _ := qb.Select("toto.main").Columns("id", "value").Where(qb.In("id")).ToCql()
	query := session.Query(statement, ids)
	defer query.Release()

	if err := query.Exec(); err != nil {
		return nil, fmt.Errorf("failed to exec the query: %w", err)
	}

	iter := query.Iter()
	log.Infof("numRows: %d", iter.NumRows())

	values, err := scan(iter, ids)
	if err != nil {
		return nil, err
	}

	for _, warning := range iter.Warnings() {
		log.Warnf("received warning from gocql client: %s", warning)
	}
	if err := iter.Close(); err != nil {
		return nil, fmt.Errorf("failed to close the CQL row iterator: %w", err)
	}
	return values, nil
}

func scan(iter *gocql.Iter, ids []uint32) (map[uint32]float64, error) {
	values := make(map[uint32]float64, len(ids))
	var (
		id uint32
		v  float64
	)
	for iter.Scan(&id, &v) {
		values[id] = v
	}
	return values, nil
}
```
Running this code with `n` less than 5000 works fine, but it fails to scan all the rows when `n` is greater than 5000.

### What did you expect to see?

I expected the (auto-)pagination to work just fine and let me read through all the rows.

### What did you see instead?

Running the code above with more than 5000 rows, say 5001, gives:

```
INFO[0000] Will write then read 5001 values             
INFO[0003] numRows: 1                                   
FATA[0003] only got 1 rows instead of 5001    
```

I did not have time to dig deeper into this but let me know if you need more details.

**Comment by martin-sucha** [comment] 2020-11-26 07:20
@vthiery thank you for reporting the issue and the nice reproducer! I was able to reproduce this issue using the code above with the latest gocql master (5913df4d474e0b2492a129d17bbb3c04537a15cd).

Seems that one of the pages is skipped for some reason (when I try with `-n 10001` then `5001` rows are returned, with `30001` I get `25001` results).

I also tried with https://github.com/gocql/gocql/pull/1508 and I can't reproduce the issue with that patch. Please check if applying that patch solves the issue for you. I don't know why exactly it fixes the issue yet (read: where the paging state is overwritten), checking that now.

**Comment by martin-sucha** [comment] 2020-11-26 07:54
Okay, after a bit more debugging I know what happens:

There is a `query.Exec` call followed by `query.Iter` call for the same query in the reproducer. Both calls execute the query on the database (`query.Exec` is implemented as `return q.Iter().Close()` internally). The first query execution overwrites the paging state in the query to point to the second page. The `Iter` call then starts iterating from the second page.

So the bug in gocql is that the `Query` struct is modified on query execution (that should be fixed by #1508).

Also, if you use `Exec` followed by `Iter` for the same query in your code in the same way as in the reproducer (as opposed to the `Exec` being in the reproducer to demonstrate Query struct reuse) I suggest removing the `Exec` call since you are basically sending the query to database twice (discarding the results in the `Exec` case).

**Comment by vthiery** [comment] 2020-11-26 08:31
Thanks @martin-sucha for the investigation! We're definitely going to fix this double query issue on our side...

**Comment by joao-r-reis** [comment] 2024-11-08 15:25
Looking at the history on this issue it looks like it can be closed, feel free to reopen it if this isn't the case

**Closed by joao-r-reis** 2024-11-08 15:25 UTC
